apiVersion: apps/v1
kind: Deployment
metadata:
  name: feproject
  namespace: dev
  labels:
    app: feproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feproject
  template:
    metadata:
      labels:
        app: feproject
    spec:
      containers:
        - name: feproject
          image: arthurfonichkin/feproject:2a9fd120567bf2014764acb5e58e6002c779969d
          ports:
            - containerPort: 80
          env: null
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
